# Uncomment the next line to define a global platform for your project
platform :ios, '9.1'

target 'ApplicationLocker' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for ApplicationLocker
    pod 'SnapKit', '~> 4.0.0'
end
